//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIStarkStartupAnimation.h"

@class FBWindowContextHostManager, UIStatusBar;

@interface _SBUIStarkStartupToAppAnimation : SBUIStarkStartupAnimation
{
    _Bool _finished;
    UIStatusBar *_fakeStatusBar;
    FBWindowContextHostManager *_contextHostManager;
}

@property(retain, nonatomic) FBWindowContextHostManager *contextHostManager; // @synthesize contextHostManager=_contextHostManager;
- (void).cxx_destruct;
- (id)_zoomInFactory;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (id)animationSettings;
- (void)_finishedAnimation:(_Bool)arg1;
- (void)_prepareAnimation;
- (id)_createViewToAnimate;

@end

