//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CCUIControlCenterSettings, NSArray, NSString, NSURL, UIView;

@protocol CCUIControlCenterSystemAgent <NSObject>
- (id <CCUIStatusBarHidingAssertion>)hideStatusBarAssertion;
- (_Bool)isUILocked;
- (UIView *)materialBackgroundView;
- (NSString *)frontmostApplicationDisplayID;
- (NSArray *)getFGSceneIdentifiers;
- (_Bool)wifiIsPowered;
- (_Bool)wifiDevicePresent;
- (void)setWifiPowered:(_Bool)arg1;
- (void)updateWifiDevicePresence;
- (_Bool)isInAirplaneMode;
- (_Bool)isOrientationLocked;
- (void)unlockOrientation;
- (void)lockOrientation;
- (_Bool)wirelessDisplayRouteIsPicked;
- (NSString *)nameOfPickedRoute;
- (_Bool)handsetRouteIsSelected;
- (void)setRingerMuted:(_Bool)arg1;
- (_Bool)isRingerMuted;
- (void)activateAppWithDisplayID:(NSString *)arg1 url:(NSURL *)arg2 unlockIfNecessary:(_Bool)arg3;
- (void)activateAppWithDisplayID:(NSString *)arg1 url:(NSURL *)arg2;
- (void)dismissAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (CCUIControlCenterSettings *)prototypeSettings;

@optional
- (void)promptForUnlockIfNecessary:(void (^)(_Bool))arg1;
@end

