//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBSceneHostManager, NSString;

@protocol FBSceneHostManagerObserver <NSObject>

@optional
- (void)sceneHostManager:(FBSceneHostManager *)arg1 willDeactivateRequester:(NSString *)arg2;
- (void)sceneHostManager:(FBSceneHostManager *)arg1 willActivateRequester:(NSString *)arg2;
- (void)sceneHostManagerDidInvalidate:(FBSceneHostManager *)arg1;
- (void)sceneHostManagerDidResumeHosting:(FBSceneHostManager *)arg1;
- (void)sceneHostManagerDidSuspendHosting:(FBSceneHostManager *)arg1;
- (void)sceneHostManagerLayersDidChange:(FBSceneHostManager *)arg1;
@end

