//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFTouchPassThroughView.h"

@interface SBAnimatableCorneredView : SBFTouchPassThroughView
{
}

@property(nonatomic) double cornerRadius;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;

@end

