//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SBApplicationTestingManager : NSObject
{
    NSString *_currentTestName;
    NSString *_scrollTestActiveSubtest;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *scrollTestActiveSubtest; // @synthesize scrollTestActiveSubtest=_scrollTestActiveSubtest;
@property(copy, nonatomic) NSString *currentTestName; // @synthesize currentTestName=_currentTestName;
- (void).cxx_destruct;

@end

