//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationServerDelegate.h"

@class NSString, SBApplicationServer;

@protocol SBApplicationServerRemovabilityDelegate <SBApplicationServerDelegate>
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 setRemovalAllowed:(_Bool)arg3 forBundleIdentifier:(NSString *)arg4;
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 fetchRemovabilityForBundleIdentifier:(NSString *)arg3 withCompletion:(void (^)(long long))arg4;
@end

