//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, SBAppSwitcherDefaults, SBApplicationController, SBIconController;

@interface SBAppSwitcherModel : NSObject
{
    NSMutableArray *_recentDisplayItems;
    NSMutableArray *_recentDisplayItemsForCommandTab;
    NSMutableDictionary *_displayItemsToRoles;
    SBAppSwitcherDefaults *_defaults;
    SBIconController *_iconController;
    SBApplicationController *_applicationController;
    id _applicationActivationStateDidChangeObserver;
    id _applicationLayoutRoleChangedNotificationObserver;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)commandTabDisplayItems;
- (id)displayItemsForAppsOfRoles:(id)arg1;
- (id)mainSwitcherDisplayItems;
- (void)remove:(id)arg1;
- (void)addToFront:(id)arg1 role:(long long)arg2;
- (id)_layoutElementForApplication:(id)arg1;
- (id)_displayItemForApplication:(id)arg1;
- (void)_addApplicationToFront:(id)arg1 role:(long long)arg2;
- (void)_applicationLayoutRoleChanged:(id)arg1;
- (void)_applicationActivationStateDidChange:(id)arg1 withLockScreenViewController:(id)arg2 andLayoutElement:(id)arg3;
- (void)_registerApplicationNotificationObservers;
- (void)_warmUpIconForDisplayItem:(id)arg1;
- (void)_warmUpRecentIcons;
- (void)_pruneRoles;
- (id)_displayItemRolesFromPrefsForLoadedDisplayItems:(id)arg1;
- (id)_recentsFromPrefs;
- (id)_recentsFromLegacyPrefs;
- (void)_saveRecents;
- (void)dealloc;
- (id)init;
- (id)initWithUserDefaults:(id)arg1 andIconController:(id)arg2 andApplicationController:(id)arg3;

@end

