//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBAppSwitcherRemoteAlertSet;

@interface SBAppSwitcherRemoteAlertManager : NSObject
{
    SBAppSwitcherRemoteAlertSet *_remoteAlerts;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)currentRemoteAlerts;
- (void)removePlaceholderForIdentifier:(id)arg1;
- (void)addPlaceholderForIdentifier:(id)arg1;
- (void)removeRemoteAlert:(id)arg1;
- (void)addRemoteAlert:(id)arg1;

@end

