//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface SBAppSwitcherSoftOutlineShadowView : UIView
{
    UIView *_clippingView;
    UIImageView *_shadowImageView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
@property(nonatomic) struct CGRect clippingFrame;
@property(nonatomic) double clippingCornerRadius;
@property(nonatomic) _Bool shouldClip;
- (id)initWithFrame:(struct CGRect)arg1;

@end

