//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BSInvalidatable.h"
#import "FBSceneMonitorDelegate.h"
#import "SBAppViewHostRequester.h"
#import "SBApplicationHosting.h"

@class FBSceneMonitor, NSMutableSet, NSSet, NSString, SBActivationSettings, SBAppView, SBApplication, SBOrientationTransformWrapperView;

@interface SBAppViewController : UIViewController <SBAppViewHostRequester, FBSceneMonitorDelegate, SBApplicationHosting, BSInvalidatable>
{
    NSString *_identifier;
    NSString *_bundleIdentifier;
    SBApplication *_hostedApp;
    SBAppView *_hostedAppView;
    SBActivationSettings *_activationSettings;
    NSMutableSet *_activeTransitions;
    NSSet *_actionsToDeliver;
    FBSceneMonitor *_sceneMonitor;
    long long _requestedMode;
    long long _currentMode;
    _Bool _ignoresOcclusions;
    _Bool _invalidated;
    _Bool _automatesLifecycle;
    unsigned long long _options;
    id <SBAppViewControllerDelegate> _delegate;
    SBOrientationTransformWrapperView *_orientationWrapperView;
}

@property(retain, nonatomic) SBOrientationTransformWrapperView *orientationWrapperView; // @synthesize orientationWrapperView=_orientationWrapperView;
@property(nonatomic) _Bool ignoresOcclusions; // @synthesize ignoresOcclusions=_ignoresOcclusions;
@property(nonatomic) __weak id <SBAppViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool automatesLifecycle; // @synthesize automatesLifecycle=_automatesLifecycle;
@property(nonatomic) long long requestedMode; // @synthesize requestedMode=_requestedMode;
@property(retain, nonatomic) NSSet *actionsToDeliver; // @synthesize actionsToDeliver=_actionsToDeliver;
@property(readonly, nonatomic) long long currentMode; // @synthesize currentMode=_currentMode;
@property(readonly, nonatomic) SBAppView *appView; // @synthesize appView=_hostedAppView;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void).cxx_destruct;
- (void)_deactivateHostedApp;
- (void)_reallyActivateApp;
- (void)_activateApp;
- (void)_sendActions:(id)arg1;
- (void)_resetOrientationWrapperView;
- (void)_destroyAppView;
- (void)_createAppView;
- (void)_setCurrentMode:(long long)arg1;
- (void)_updateForAppearanceState:(int)arg1;
- (void)sceneMonitor:(id)arg1 sceneSettingsDidChangeWithDiff:(id)arg2 previousSettings:(id)arg3;
- (void)sceneMonitor:(id)arg1 sceneWasDestroyed:(id)arg2;
- (long long)appViewRequesterPriority:(id)arg1;
- (id)appViewRequesterIdentifier:(id)arg1;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)arg1;
- (id)hostedApp;
- (_Bool)isHostingAnApp;
- (_Bool)canHostAnApp;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)invalidate;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1 andApplication:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

