//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBCarDisplaySettings : SBUISettings
{
    _Bool _animateLockOutModeChanges;
    long long _lockOutMode;
}

+ (id)settingsControllerModule;
@property long long lockOutMode; // @synthesize lockOutMode=_lockOutMode;
@property _Bool animateLockOutModeChanges; // @synthesize animateLockOutModeChanges=_animateLockOutModeChanges;
- (void)setDefaultValues;

@end

