//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class SBIconBlurryBackgroundView, SBIconColorSettings, UIImageView, UIView;

@interface SBCloseBoxView : UIButton
{
    SBIconBlurryBackgroundView *_backgroundView;
    UIView *_whiteTintView;
    UIImageView *_xColorBurnView;
    UIImageView *_xPlusDView;
    SBIconColorSettings *_colorSettings;
    struct CGPoint _wallpaperRelativeCenter;
}

- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setSuppressesBlurryBackgroundChanges:(_Bool)arg1;
- (void)setLegibilityStyle:(long long)arg1;
- (void)setWallpaperRelativeCenter:(struct CGPoint)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

