//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCUIControlCenterSystemAgent.h"

@class NSHashTable, NSString;

@interface SBControlCenterSystemAgent : NSObject <CCUIControlCenterSystemAgent>
{
    NSHashTable *_weakWallpaperBackgroundViews;
}

- (void).cxx_destruct;
- (id)hideStatusBarAssertion;
- (_Bool)isUILocked;
- (void)_controlCenterDidDismiss:(id)arg1;
- (void)_controlCenterWillPresent:(id)arg1;
- (id)materialBackgroundView;
- (id)frontmostApplicationDisplayID;
- (id)getFGSceneIdentifiers;
- (_Bool)wifiIsPowered;
- (_Bool)wifiDevicePresent;
- (void)setWifiPowered:(_Bool)arg1;
- (void)updateWifiDevicePresence;
- (_Bool)isInAirplaneMode;
- (_Bool)isOrientationLocked;
- (void)unlockOrientation;
- (void)lockOrientation;
- (_Bool)wirelessDisplayRouteIsPicked;
- (id)nameOfPickedRoute;
- (_Bool)handsetRouteIsSelected;
- (void)setRingerMuted:(_Bool)arg1;
- (_Bool)isRingerMuted;
- (void)promptForUnlockIfNecessary:(CDUnknownBlockType)arg1;
- (void)activateAppWithDisplayID:(id)arg1 url:(id)arg2 unlockIfNecessary:(_Bool)arg3;
- (void)activateAppWithDisplayID:(id)arg1 url:(id)arg2;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)prototypeSettings;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

