//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CCUIControlCenterViewControllerDelegate.h"
#import "SBCoordinatedPresenting.h"
#import "SBDashBoardExternalBehaviorProviding.h"
#import "SBDashBoardExternalPresentationProviding.h"
#import "SBSystemGestureRecognizerDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class CCUIControlCenterRootView, CCUIControlCenterViewController, FBDisplayLayoutElement, FBUIApplicationSceneDeactivationAssertion, NSArray, NSHashTable, NSMutableSet, NSSet, NSString, SBControlCenterSystemAgent, SBScreenEdgePanGestureRecognizer, SBUIChevronView, SBWindow, UIDynamicAnimator, UIImageView, UIView, _UIBackdropView, _UIDynamicValueAnimation, _UIFeedbackEdgeBehavior;

@interface SBControlCenterController : UIViewController <CCUIControlCenterViewControllerDelegate, UIGestureRecognizerDelegate, SBSystemGestureRecognizerDelegate, SBDashBoardExternalBehaviorProviding, SBDashBoardExternalPresentationProviding, SBCoordinatedPresenting>
{
    SBWindow *_window;
    CCUIControlCenterRootView *_rootView;
    CCUIControlCenterViewController *_viewController;
    UIImageView *_coveredContentSnapshot;
    UIView *_fullScreenGrabberContainer;
    _UIBackdropView *_fullScreenGrabberBackdrop;
    SBUIChevronView *_fullScreenChevron;
    SBScreenEdgePanGestureRecognizer *_controlCenterGestureRecognizer;
    double _controlCenterGestureStartTime;
    SBControlCenterSystemAgent *_systemAgent;
    FBUIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    FBDisplayLayoutElement *_displayLayoutElement;
    NSMutableSet *_preventDismissalOnLockReasons;
    _Bool _uiLocked;
    NSHashTable *_observers;
    long long _orientation;
    _Bool _animatingInitialSwipe;
    _Bool _inPresentationPan;
    _Bool _inDismissalPan;
    struct CGPoint _panInitialTouchLocation;
    _Bool _dismissalPanHasGoneBelowCCTopEdge;
    _Bool _gotFirstBackdropUpdate;
    _UIDynamicValueAnimation *_bounceAnimation;
    UIDynamicAnimator *_animator;
    unsigned long long _animatorStopCount;
    struct CGRect _animatorStopFrame;
    _Bool _presented;
    _Bool _inGrabberOnlyMode;
    _Bool _transitioning;
    _Bool _fullyRevealed;
    double _ambiguousActivationMargin;
    _UIFeedbackEdgeBehavior *_feedbackBehavior;
}

+ (void)notifyControlCenterControl:(id)arg1 didActivate:(_Bool)arg2;
+ (double)transitionAnimationDuration;
+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreatingIfNeeded:(_Bool)arg1;
@property(retain, nonatomic) _UIFeedbackEdgeBehavior *feedbackBehavior; // @synthesize feedbackBehavior=_feedbackBehavior;
@property(nonatomic, getter=_ambiguousActivationMargin) double ambiguousActivationMargin; // @synthesize ambiguousActivationMargin=_ambiguousActivationMargin;
@property(nonatomic, getter=isFullyRevealed) _Bool fullyRevealed; // @synthesize fullyRevealed=_fullyRevealed;
@property(nonatomic, getter=isTransitioning) _Bool transitioning; // @synthesize transitioning=_transitioning;
@property(nonatomic) _Bool inGrabberOnlyMode; // @synthesize inGrabberOnlyMode=_inGrabberOnlyMode;
@property(nonatomic, getter=isPresented) _Bool presented; // @synthesize presented=_presented;
@property(nonatomic, getter=isUILocked) _Bool UILocked; // @synthesize UILocked=_uiLocked;
- (void).cxx_destruct;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)beginTransitionWithTouchLocation:(struct CGPoint)arg1;
- (void)scrollToPage:(unsigned long long)arg1 animated:(_Bool)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (unsigned long long)numberOfActivePages;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long scrollingStrategy;
@property(readonly, copy, nonatomic) NSArray *presentationRegions;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> presentationCoordinateSpace;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (id)controlCenterSystemAgentForControlCenterViewController:(id)arg1;
- (void)controlCenterViewController:(id)arg1 backdropViewDidUpdate:(id)arg2;
- (void)controlCenterViewController:(id)arg1 handlePan:(id)arg2;
- (void)controlCenterViewController:(id)arg1 handleTap:(id)arg2;
- (_Bool)controlCenterViewController:(id)arg1 canHandleGestureRecognizer:(id)arg2;
- (void)controlCenterViewControllerWantsDismissal:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)controlCenterViewControllerWantsDismissal:(id)arg1;
- (void)abortAnimatedTransition;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 wasCancelled:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateTransitionWithTouchLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (void)beginPresentationWithTouchLocation:(struct CGPoint)arg1 presentationBegunHandler:(CDUnknownBlockType)arg2;
- (_Bool)isPresentingControllerTransitioning;
@property(readonly, nonatomic) unsigned long long hintEdge;
@property(readonly, nonatomic) double hintDisplacement;
@property(readonly, nonatomic) long long coordinatedPresentingControllerIdentifier;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)viewForSystemGestureRecognizer:(id)arg1;
- (void)_hideGrabberForSystemGesture;
- (void)_updateShouldShowGrabberOnFirstSwipe;
- (_Bool)_shouldShowGrabberOnFirstSwipe;
- (void)hideGrabberAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)hideGrabberAnimated:(_Bool)arg1;
- (void)showGrabberAnimated:(_Bool)arg1;
- (void)_finishPresenting:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_dismissWithDuration:(double)arg1 additionalAnimations:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissAnimated:(_Bool)arg1 withAdditionalAnimations:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissAnimated:(_Bool)arg1;
- (void)_presentWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentAnimated:(_Bool)arg1;
- (void)presentAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_resetPanTransitionState;
- (void)_cancelTransition;
- (void)_endTransitionWithVelocity:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (double)_verticalPercentageMovedOnScreenForY:(double)arg1 stopY:(double)arg2;
- (void)_cleanupAnimator;
- (id)_newDynamicAnimationForShow:(_Bool)arg1 currentValue:(double)arg2 velocity:(double)arg3 unitSize:(double)arg4;
- (void)_updateTransitionWithTouchLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (void)_beginTransitionWithTouchLocation:(struct CGPoint)arg1;
- (void)_doSetupBeforeBeginTransition;
- (void)_endPresentation;
- (void)_beginPresentation;
- (void)_setupViewForPresentation;
- (_Bool)allowHideTransition;
- (_Bool)allowShowTransitionSystemGesture;
- (_Bool)_allowShowTransitionSystemGesture;
- (_Bool)allowShowTransition;
- (void)_beginSystemGesturePresentationWithGestureRecognizer:(id)arg1;
- (void)_showControlCenterGestureCancelled;
- (void)_showControlCenterGestureFailed;
- (void)_showControlCenterGestureEndedWithGestureRecognizer:(id)arg1;
- (void)_showControlCenterGestureChangedWithGestureRecognizer:(id)arg1;
- (void)_showControlCenterGestureBeganWithGestureRecognizer:(id)arg1;
- (void)_handleShowControlCenterGesture:(id)arg1;
- (id)_controlCenterViewController;
- (void)_clearCoveredContentSnapshot;
- (void)_updateCoveredContentSnapshot;
- (void)_setLockHUDHidden:(_Bool)arg1;
- (void)_updateGrabberVisibility;
- (void)_updateRevealPercentage:(double)arg1;
- (void)_revealSlidingViewToHeight:(double)arg1;
- (double)_controlCenterHeightForTouchLocation:(struct CGPoint)arg1 initialTouchLocation:(struct CGPoint)arg2;
- (double)_yValueForClosed;
- (double)_yValueForOpen;
- (void)_uiRelockedNotification:(id)arg1;
- (void)_lockStateChangedNotification:(id)arg1;
- (_Bool)_shouldUseControlCenterRevealConfirmation;
- (void)_dismissOnLock;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (_Bool)wantsFullScreenLayout;
- (void)setAmbiguousActivationMargin:(double)arg1 forApp:(id)arg2;
- (id)_controlCenterWindow;
- (void)preventDismissalOnLock:(_Bool)arg1 forReason:(id)arg2;
- (_Bool)isGrabberVisible;
- (_Bool)isVisible;
- (_Bool)handleMenuButtonTap;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_enumerateObservers:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) NSSet *conflictingGestures;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSSet *gestures;
@property(readonly) unsigned long long hash;
@property(nonatomic) id <SBPresentingDelegate> presentingDelegate;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSSet *tapExcludedViews;

@end

