//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBDashBoardBackgroundStyleTransitioning.h"
#import "SBDashBoardWallpaperOverlay.h"

@class NSString, SBBackdropView;

@interface SBDashBoardBackgroundView : UIView <SBDashBoardBackgroundStyleTransitioning, SBDashBoardWallpaperOverlay>
{
    long long _style;
    long long _transitionStyle;
    _Bool _transitioning;
    double _progress;
    SBBackdropView *_backdropView;
    UIView *_reduceTransparencyView;
    UIView *_sourceOverView;
    UIView *_darkenSourceOverView;
    UIView *_tintView;
}

@property(readonly, nonatomic) SBBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(readonly, nonatomic, getter=isTransitioningBackgroundStyle) _Bool transitioningBackgroundStyle; // @synthesize transitioningBackgroundStyle=_transitioning;
@property(nonatomic) long long backgroundStyle; // @synthesize backgroundStyle=_style;
- (void).cxx_destruct;
- (double)_valueFromStart:(double)arg1 toEnd:(double)arg2 withFraction:(double)arg3;
- (id)_backgroundColorForDarkenAlpha:(double)arg1 andProgress:(double)arg2;
- (void)_reduceTransparencyWithProgress:(double)arg1;
- (void)_tintWithProgress:(double)arg1;
- (void)_darkenWithProgress:(double)arg1;
- (double)_reducedTransparencyValueForBackgroundStyle:(long long)arg1;
- (double)_tintValueForBackgroundStyle:(long long)arg1;
- (double)_darkenValueForBackgroundStyle:(long long)arg1;
- (void)_updateAppearanceForTransitionFromStyle:(long long)arg1 toStyle:(long long)arg2 withProgress:(double)arg3;
- (void)_updateAppearanceForBackgroundStyle:(long long)arg1 transitionToSettings:(_Bool)arg2;
@property(retain, nonatomic) NSString *groupName;
- (void)completeTransitionToBackgroundStyle:(long long)arg1;
- (void)updateBackgroundStyleTransitionProgress:(double)arg1;
- (void)beginTransitionToBackgroundStyle:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

