//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardNowPlayingViewController.h"

@class UIView;

@interface SBDashBoardMediaArtworkViewController : SBDashBoardNowPlayingViewController
{
    UIView *_artworkView;
}

+ (Class)viewClass;
- (void).cxx_destruct;
- (long long)scrollingStrategy;
- (long long)presentationPriority;
- (long long)presentationType;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithArtworkView:(id)arg1;

@end

