//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, SBUICallToActionLabel, UIButton, UILabel;

@interface SBDashBoardSetupView : UIView
{
    UILabel *_titleLabel;
    int _viewState;
    UIView *_activationInfoView;
    UIButton *_infoButton;
    SBUICallToActionLabel *_callToActionLabel;
    NSString *_titleString;
    NSString *_language;
    UIView *_regulatoryInfoView;
}

@property(retain, nonatomic) UIView *regulatoryInfoView; // @synthesize regulatoryInfoView=_regulatoryInfoView;
@property(nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) NSString *titleString; // @synthesize titleString=_titleString;
@property(nonatomic) int viewState; // @synthesize viewState=_viewState;
@property(retain, nonatomic) SBUICallToActionLabel *callToActionLabel; // @synthesize callToActionLabel=_callToActionLabel;
@property(retain, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) UIView *activationInfoView; // @synthesize activationInfoView=_activationInfoView;
- (void).cxx_destruct;
- (void)_setupConstraints;
- (void)layoutSubviews;
- (void)_setLanguage:(id)arg1 forLabel:(id)arg2;
- (void)_toggleViewState;
- (void)_adjustTitleVisibilityForInfoViews;
- (void)setTitleString:(id)arg1 forLanguage:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

