//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBAppViewControllerDelegate.h"
#import "SBApplicationHosting.h"

@class FBUIApplicationSceneDeactivationAssertion, NSSet, NSString, SBAppView, SBAppViewController, SBFAuthenticationAssertion;

@interface SBDashBoardHostedAppViewController : SBDashBoardViewControllerBase <SBAppViewControllerDelegate, SBApplicationHosting>
{
    id <SBDashBoardHostedAppViewControllerDelegate> _delegate;
    SBAppViewController *_appViewController;
    FBUIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    SBFAuthenticationAssertion *_authenticationAssertion;
    NSString *_cachedBasicPublicDescription;
}

@property(nonatomic) __weak id <SBDashBoardHostedAppViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setResignActiveAssertionEnabled:(_Bool)arg1;
- (void)_setMode:(long long)arg1 fromClient:(_Bool)arg2 forReason:(id)arg3;
- (void)appViewController:(id)arg1 didTransitionFromMode:(long long)arg2 toMode:(long long)arg3;
- (void)appViewControllerDidDeactivateApplication:(id)arg1;
- (void)appViewControllerWillActivateApplication:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)arg1;
- (id)hostedApp;
- (_Bool)isHostingAnApp;
- (_Bool)canHostAnApp;
- (long long)presentationPriority;
- (long long)presentationType;
- (long long)presentationStyle;
- (id)appearanceIdentifier;
- (void)configureDisplayLayoutElement:(id)arg1;
- (id)displayLayoutElementIdentifier;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(retain, nonatomic) NSSet *actionsToDeliver;
@property(nonatomic) unsigned long long options;
@property(readonly, nonatomic) SBAppView *appView;
@property(nonatomic) long long mode;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier;
- (void)dealloc;
- (id)initWithApplication:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

