//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSLogPlistStateCapturing.h"
#import "SBDashBoardEventHandling.h"
#import "SBIdleTimerDelegate.h"

@class NSMutableSet, NSString, SBDashBoardIdleTimerFactory;

@interface SBDashBoardIdleTimerEventPublisher : NSObject <SBIdleTimerDelegate, BSLogPlistStateCapturing, SBDashBoardEventHandling>
{
    id <SBDashBoardEventHandling> _eventHandler;
    SBDashBoardIdleTimerFactory *_idleTimerFactory;
    id <SBIdleTimer> _idleTimer;
    id <SBIdleTimer> _disabledTimer;
    NSMutableSet *_disabledAssertions;
}

- (void).cxx_destruct;
- (id)stateCapturePlist;
- (void)idleTimerDidWarn:(id)arg1;
- (void)idleTimerDidReceiveUserEvent:(id)arg1;
- (void)idleTimerDidExpire:(id)arg1;
- (void)idleTimerDidRefresh:(id)arg1;
- (_Bool)wouldHandleButtonEvent:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (_Bool)isEnabled;
- (_Bool)isDisabledAssertionActiveForReason:(id)arg1;
- (void)removeDisabledAssertionReason:(id)arg1;
- (void)addDisabledAssertionReason:(id)arg1;
- (void)updateWithIdleDimProvider:(id)arg1 reason:(id)arg2;
- (void)reset;
- (id)initWithEventHandler:(id)arg1 idleTimerFactory:(id)arg2;
- (id)initWithEventHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

