//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBDisconnectAccessoryViewDelegate.h"

@class NSString;

@interface SBDashBoardDisconnectAccessoryViewController : SBDashBoardViewControllerBase <SBDisconnectAccessoryViewDelegate>
{
}

+ (Class)viewClass;
- (void)_updateViewMode;
- (void)_resetIdleTimer;
- (void)didPerformActionForDisconnectAccessoryView:(id)arg1;
- (void)didInteractWithDisconnectAccessoryView:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (long long)presentationPriority;
- (long long)presentationType;
- (long long)presentationStyle;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

