//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSwitcherWallpaperPageContentView.h"

@class SBAppView, SBDisplayItem, SBOrientationTransformWrapperView, SBZoomableCrossfadeView, UIImageView, UILabel, UIView;

@interface SBDeckSwitcherAppSuggestionPageContentView : SBSwitcherWallpaperPageContentView
{
    UIView *_contentView;
    UIImageView *_imageView;
    UILabel *_topLabel;
    UILabel *_bottomLabel;
    SBAppView *_zoomUpAppView;
    SBDisplayItem *_displayItem;
    SBZoomableCrossfadeView *_zoomUpCrossfadeView;
    SBOrientationTransformWrapperView *_appViewLayoutWrapper;
}

- (void).cxx_destruct;
- (void)viewDismissing:(id)arg1 withInteraction:(_Bool)arg2 andInitialProgress:(double)arg3 forTransitionRequest:(id)arg4;
- (void)viewPresenting:(id)arg1 withInteraction:(_Bool)arg2 andInitialProgress:(double)arg3 forTransitionRequest:(id)arg4;
- (void)layoutSubviews;
- (id)_firstWakeGreetingString;
- (id)_meCardShortName;
- (id)_bottomStringForSuggestion:(id)arg1;
- (id)_topStringForSuggestion:(id)arg1;
- (id)_imageForSuggestion:(id)arg1;
- (void)_configureImageAndLabelsForSuggestion:(id)arg1;
- (void)invalidate;
- (id)initWithFrame:(struct CGRect)arg1 displayItem:(id)arg2 suggestedApp:(id)arg3;

@end

