//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, SBDisplayItem, SBIcon, UIImageView;

@interface SBDeckSwitcherIconImageContainerView : UIView
{
    SBDisplayItem *_displayItem;
    SBIcon *_icon;
    UIImageView *_imageView;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) SBIcon *icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) SBDisplayItem *displayItem; // @synthesize displayItem=_displayItem;
- (void).cxx_destruct;
- (void)_crossfadeToIconImage:(id)arg1;
- (void)_configureIconImageView:(id)arg1;
@property(readonly, nonatomic) NSString *displayName;
- (void)updateIcon;
- (void)layoutSubviews;
- (id)initWithDisplayItem:(id)arg1;

@end

