//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UIVisualEffectView;

@interface SBFolderControllerBackgroundView : UIView
{
    UIVisualEffectView *_blurView;
    UIImageView *_blurViewSnapshot;
    UIView *_reduceTransparencyTintView;
    UIView *_debugFreezingView;
    _Bool _transitionCancelled;
    _Bool _blurs;
    _Bool _expanding;
    _Bool _frozen;
}

+ (double)blurRadiusForBackgroundViewInView:(id)arg1;
@property(nonatomic) _Bool frozen; // @synthesize frozen=_frozen;
@property(nonatomic) _Bool expanding; // @synthesize expanding=_expanding;
@property(nonatomic) _Bool blurs; // @synthesize blurs=_blurs;
@property(nonatomic) _Bool transitionCancelled; // @synthesize transitionCancelled=_transitionCancelled;
- (void).cxx_destruct;
- (void)_updateEffect;
- (id)_effectiveEmptyEffect;
- (id)_blurEffect;
- (double)_effectScale;
- (void)layoutSubviews;
- (void)_updateForHavingReduceTransparencyOn:(_Bool)arg1;
- (void)_reduceTransparencyEnabledStateChanged;
- (id)initWithFrame:(struct CGRect)arg1;

@end

