//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBAnimationSettings;

@interface SBIconAnimationSettings : SBUISettings
{
    SBAnimationSettings *_centralAnimationSettings;
}

+ (id)settingsControllerModule;
@property(retain) SBAnimationSettings *centralAnimationSettings; // @synthesize centralAnimationSettings=_centralAnimationSettings;
- (void).cxx_destruct;
- (id)centralAnimationSettingsWithAdditionalDelays;
- (void)setDefaultValues;

@end

