//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SBInfoOperation : NSObject
{
    id _operand;
    NSString *_label;
}

+ (id)operationWithOperand:(id)arg1 label:(id)arg2;
@property(readonly, nonatomic) id operand; // @synthesize operand=_operand;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithOperand:(id)arg1 label:(id)arg2;

@end

