//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SBLayoutElementPinResizeGrabberView : UIView
{
    UIView *_vibrantView;
    UIView *_solidView;
    _Bool _vibrant;
}

@property(nonatomic, getter=isVibrant) _Bool vibrant; // @synthesize vibrant=_vibrant;
- (void).cxx_destruct;
- (void)layoutSubviews;
@property(nonatomic, getter=isVisible) _Bool visible;
- (void)_createVibrantVersionIfNeeded;
- (id)init;

@end

