//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBLockScreenMesaFailureSettings;

@interface SBLockScreenMesaSettings : SBUISettings
{
    _Bool _passcodeRequiredEventsCountAsFailures;
    _Bool _flashRedOnPasscodeRequiredEvents;
    _Bool _successFeedbackWaitsUntilButtonUp;
    SBLockScreenMesaFailureSettings *_firstFailureSettings;
    SBLockScreenMesaFailureSettings *_secondFailureSettings;
    SBLockScreenMesaFailureSettings *_thirdFailureSettings;
    SBLockScreenMesaFailureSettings *_fourthFailureSettings;
    SBLockScreenMesaFailureSettings *_fifthFailureSettings;
    double _slowPressDuration;
}

+ (id)settingsControllerModule;
@property(nonatomic) double slowPressDuration; // @synthesize slowPressDuration=_slowPressDuration;
@property(nonatomic) _Bool successFeedbackWaitsUntilButtonUp; // @synthesize successFeedbackWaitsUntilButtonUp=_successFeedbackWaitsUntilButtonUp;
@property(nonatomic) _Bool flashRedOnPasscodeRequiredEvents; // @synthesize flashRedOnPasscodeRequiredEvents=_flashRedOnPasscodeRequiredEvents;
@property(nonatomic) _Bool passcodeRequiredEventsCountAsFailures; // @synthesize passcodeRequiredEventsCountAsFailures=_passcodeRequiredEventsCountAsFailures;
@property(retain, nonatomic) SBLockScreenMesaFailureSettings *fifthFailureSettings; // @synthesize fifthFailureSettings=_fifthFailureSettings;
@property(retain, nonatomic) SBLockScreenMesaFailureSettings *fourthFailureSettings; // @synthesize fourthFailureSettings=_fourthFailureSettings;
@property(retain, nonatomic) SBLockScreenMesaFailureSettings *thirdFailureSettings; // @synthesize thirdFailureSettings=_thirdFailureSettings;
@property(retain, nonatomic) SBLockScreenMesaFailureSettings *secondFailureSettings; // @synthesize secondFailureSettings=_secondFailureSettings;
@property(retain, nonatomic) SBLockScreenMesaFailureSettings *firstFailureSettings; // @synthesize firstFailureSettings=_firstFailureSettings;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

