//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBMainWorkspaceTransaction.h"

#import "BSTransactionObserver.h"
#import "FBSynchronizedTransactionDelegate.h"

@class NSString, SBWorkspaceTransaction;

@interface SBLockScreenSlideUpToAppWorkspaceTransaction : SBMainWorkspaceTransaction <BSTransactionObserver, FBSynchronizedTransactionDelegate>
{
    _Bool _launchedApp;
    SBWorkspaceTransaction *_earlyLaunchTransaction;
    SBWorkspaceTransaction *_deferredFinalLaunchTransaction;
    _Bool _gestureCompleted;
    _Bool _didBegin;
    _Bool _notifiedSlaves;
}

- (void).cxx_destruct;
- (void)_notifySlavesIfNecessary;
- (void)synchronizedTransaction:(id)arg1 didCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransaction:(id)arg1 willCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransactionReadyToCommit:(id)arg1;
- (void)addSlaveTransaction:(id)arg1;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)launchAppUnderLockScreenWithTransaction:(id)arg1;
- (void)noteGestureCompletedSuccessfully:(_Bool)arg1 cleanupTransaction:(id)arg2;
- (_Bool)isGestureCompleted;
- (void)_begin;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

