//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBLockScreenPluginTransitionFactory : NSObject
{
}

+ (_Bool)_shouldAnimateTransitionFromPlugin:(id)arg1 toPlugin:(id)arg2;
+ (id)transitionFromPlugin:(id)arg1 toPlugin:(id)arg2 lockScreenViewController:(id)arg3;

@end

