//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

#import "SBAutoUnlockRule.h"
#import "SBMesaUnlockBehavior.h"
#import "SBScreenFadeAnimationControllerDelegate.h"

@class NSString, SBLockScreenActionContext;

@interface SBLockScreenViewControllerBase : SBAlert <SBScreenFadeAnimationControllerDelegate, SBAutoUnlockRule, SBMesaUnlockBehavior>
{
    SBLockScreenActionContext *_customLockScreenActionContext;
    _Bool _authenticated;
    double _backlightLevel;
    id <SBMesaUnlockBehaviorDelegate> _mesaUnlockBehaviorDelegate;
}

@property(nonatomic, getter=isAuthenticated) _Bool authenticated; // @synthesize authenticated=_authenticated;
@property(nonatomic) __weak id <SBMesaUnlockBehaviorDelegate> mesaUnlockBehaviorDelegate; // @synthesize mesaUnlockBehaviorDelegate=_mesaUnlockBehaviorDelegate;
@property(nonatomic) double backlightLevel; // @synthesize backlightLevel=_backlightLevel;
- (void).cxx_destruct;
- (void)handleBiometricEvent:(unsigned long long)arg1;
- (_Bool)shouldAutoUnlockForSource:(int)arg1;
- (void)screenFadeAnimationController:(id)arg1 setRelevantViewsHidden:(_Bool)arg2 forRequester:(id)arg3;
- (_Bool)shouldUnlockUIOnKeyDownEvent;
- (void)noteResetRestoreStateUpdated;
- (void)noteDeviceBlockedStatusUpdated;
- (_Bool)wantsLockScreenIdleTimer;
- (_Bool)isMainPageVisible;
- (_Bool)isShowingOverheatUI;
- (id)createHomeButtonShowPasscodeRecognizerForHomeButtonPress;
- (void)didCompleteTransitionOutOfLockScreen;
- (_Bool)isSystemGesturePermittedForPresentingController:(id)arg1;
- (void)shakeSlideToUnlockTextWithCustomText:(id)arg1;
- (void)setShowingMediaControls:(_Bool)arg1;
- (_Bool)isShowingMediaControls;
- (void)updateOrientationForUndim;
- (void)setCustomLockScreenActionContext:(id)arg1;
- (id)_customLockScreenActionContext;
- (id)currentLockScreenActionContext;
- (void)noteModalBannerIsVisible:(_Bool)arg1;
- (_Bool)lockScreenIsShowingBulletins;
- (_Bool)shouldShowStatusBarOnDeactivation;
- (_Bool)shouldShowLockStatusBarTime;
- (_Bool)shouldDisableALS;
- (_Bool)shouldShowSlideshowButton;
- (void)noteMenuButtonUp;
- (void)noteMenuButtonDown;
- (_Bool)handleMenuButtonHeld;
- (_Bool)handleMenuButtonTap;
- (void)noteExitingLostMode;
- (void)prepareToEnterLostMode;
- (void)_handlePassKitDismissal;
- (void)_handlePassKitPresentation;
- (void)updateCardItem:(id)arg1;
- (void)deactivateCardItem:(id)arg1;
- (void)activateCardItem:(id)arg1 animated:(_Bool)arg2;
- (void)disableLockScreenPluginWithContext:(id)arg1;
- (void)enableLockScreenPluginWithContext:(id)arg1;
- (void)setInScreenOffMode:(_Bool)arg1 forAutoUnlock:(_Bool)arg2;
- (void)setInScreenOffMode:(_Bool)arg1;
- (_Bool)isInScreenOffMode;
- (void)startLockScreenFadeInAnimationForSource:(int)arg1;
- (_Bool)canRelockForAutoDimTimer;
- (_Bool)wantsScreenToAutoDim;
- (void)prepareForMesaUnlockWithCompletion:(CDUnknownBlockType)arg1;
- (void)noteNextUnlockShouldReturnToCallIfPossible:(_Bool)arg1;
- (_Bool)isHidingPasscodeViewDuringCall;
- (void)setForcesPasscodeViewDuringCall:(_Bool)arg1;
- (void)noteStartingPhoneCallWhileUILocked;
- (_Bool)isMakingEmergencyCall;
- (void)emergencyDialerExitedWithError:(id)arg1;
- (void)exitEmergencyDialerAnimated:(_Bool)arg1;
- (void)launchEmergencyDialer;
- (void)launchInCallAlert;
- (void)activateCameraAnimated:(_Bool)arg1;
- (void)activateCamera;
- (id)_displayLayoutElementIdentifier;
- (_Bool)allowsStackingOfAlert:(id)arg1;
- (void)willBeginDeactivationForTransitionToApps:(id)arg1 animated:(_Bool)arg2;
- (_Bool)_isLockAlert;
- (void)prepareForExternalUIUnlock;
- (void)deactivate;
- (void)activate;
- (void)finishUIUnlockFromSource:(int)arg1;
- (void)attemptToUnlockUIFromNotification;
- (_Bool)canBeDeactivatedForUIUnlockFromSource:(int)arg1;
- (_Bool)canUIUnlockFromSource:(int)arg1;
- (void)prepareForUIUnlock;
- (_Bool)isUnlockDisabled;
- (void)setPasscodeLockVisible:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setPasscodeLockVisible:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)isPasscodeLockVisible;
- (void)updateStatusBarForLockScreenTeardown;
- (void)updateLegibility;
- (_Bool)allowSystemGestureAtLocation:(struct CGPoint)arg1;
- (void)_transitionWallpaperFromLockWithOptionalOutTimingFunction:(id)arg1 adjustWindowLevel:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_transitionWallpaperFromLock;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

