//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class SBUILegibilityLabel;

@interface SBLockScreenStatusTextViewController : UIViewController
{
    SBUILegibilityLabel *_textLabel;
}

- (void).cxx_destruct;
- (id)_legalString;
- (void)updateTextView;
- (void)didMoveToParentViewController:(id)arg1;
- (id)statusTextView;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

