//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SBMainDisplayInterfaceOrientationAggregator : NSObject
{
}

- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)description;
- (id)_highestSourceAtOrBelow:(double)arg1 amongSources:(id)arg2;
- (void)_sortSources:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *interfaceOrientationSources;
@property(readonly, nonatomic) long long activeInterfaceOrientation;
- (long long)_layoutOrientation;

@end

