//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface SBModeControlManager : NSObject
{
    NSMutableArray *_views;
}

+ (id)_segmentedControlForUse:(long long)arg1 colorSettings:(id)arg2;
+ (void)_configureSegmentedControl:(id)arg1 withColorSettings:(id)arg2;
@property(readonly, nonatomic) NSArray *views; // @synthesize views=_views;
- (void).cxx_destruct;
- (void)setTintColor:(id)arg1 forUse:(long long)arg2;
- (void)removeAllSegments;
- (void)insertSegmentWithTitle:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
@property(nonatomic) long long selectedSegmentIndex;
@property(readonly, nonatomic) unsigned long long numberOfSegments;
- (id)_segmentedControlForUse:(long long)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithGraphicsQuality:(long long)arg1;

@end

