//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NCNotificationListViewControllerDestinationDelegate.h"
#import "NCNotificationListViewControllerUserInteractionDelegate.h"
#import "SBAlertingNotificationDestination.h"
#import "SBNotificationDestinationHomeButtonPressHandler.h"

@class NCNotificationListContainerViewController, NCNotificationListViewController, NSString, SBNCAlertingController;

@interface SBNotificationCenterDestination : NSObject <NCNotificationListViewControllerDestinationDelegate, NCNotificationListViewControllerUserInteractionDelegate, SBAlertingNotificationDestination, SBNotificationDestinationHomeButtonPressHandler>
{
    id <NCNotificationDestinationDelegate> _delegate;
    SBNCAlertingController *_alertingController;
    NCNotificationListViewController *_notificationListViewController;
    NCNotificationListContainerViewController *_notificationsContainerViewController;
}

@property(retain, nonatomic) NCNotificationListContainerViewController *notificationsContainerViewController; // @synthesize notificationsContainerViewController=_notificationsContainerViewController;
@property(retain, nonatomic) NCNotificationListViewController *notificationListViewController; // @synthesize notificationListViewController=_notificationListViewController;
@property(nonatomic) __weak SBNCAlertingController *alertingController; // @synthesize alertingController=_alertingController;
@property(nonatomic) __weak id <NCNotificationDestinationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_shouldHidePreviewForNotificationRequest:(id)arg1;
- (void)_hideOrShowRequestsForParentNotificationSectionSettings:(id)arg1;
- (void)_hideOrShowRequestsForNotificationSectionSettings:(id)arg1;
- (_Bool)_notificationSectionSettingsHidesSection:(id)arg1;
- (_Bool)_isNotAuthenticated;
- (void)_lockStateChanged:(id)arg1;
- (id)notificationListViewController:(id)arg1 staticContentProviderForNotificationRequest:(id)arg2 viewController:(id)arg3;
- (_Bool)notificationListViewController:(id)arg1 showSupplementaryActionsForNotificationRequest:(id)arg2;
- (void)notificationListViewController:(id)arg1 requestsClearingNotificationRequests:(id)arg2;
- (void)notificationListViewController:(id)arg1 requestsExecuteAction:(id)arg2 forNotificationRequest:(id)arg3 withParameters:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)notificationListViewController:(id)arg1 requestPermissionToExecuteAction:(id)arg2 forNotificationRequest:(id)arg3 withParameters:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)notificationListViewController:(id)arg1 shouldFinishLongLookTransitionForNotification:(id)arg2 withCompletionBlock:(CDUnknownBlockType)arg3;
- (struct CGRect)notificationListViewController:(id)arg1 convertRect:(struct CGRect)arg2 toLocalWindowSpaceFromView:(id)arg3;
- (id)notificationListViewController:(id)arg1 preferredViewControllerForPresentingFromViewController:(id)arg2;
- (void)notificationListViewControllerDidFinishSignificantUserInteraction:(id)arg1;
- (void)notificationListViewControllerDidBeginSignificantUserInteraction:(id)arg1;
- (void)notificationListViewControllerDidSignificantUserInteraction:(id)arg1;
- (_Bool)isNotificationContentExtensionVisible:(id)arg1;
- (void)updateNotificationSectionSettings:(id)arg1;
- (void)withdrawNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)modifyNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)postNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (_Bool)canReceiveNotificationRequest:(id)arg1;
@property(readonly, nonatomic) NSString *identifier;
- (_Bool)handleHomeButtonPress;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

