//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBBulletinActionHandler.h"
#import "SBDashBoardExternalBehaviorProviding.h"
#import "SBNCTableViewControllerDelegate.h"
#import "SBNotificationCenterWithSearchViewControllerPresentationDelegate.h"
#import "SBReachabilityObserver.h"
#import "SBSearchEtceteraMultiplexingViewControllerAppearanceDelegate.h"
#import "SBUISizeObservingViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSSet, NSString, SBNotificationCenterLayoutViewController, SBNotificationCenterScrollToTopView, SBNotificationCenterWithSearchViewController, SBNotificationSeparatorView, SBUIChevronView, UIGestureRecognizer, UIStatusBar, UIView, _UIBackdropView;

@interface SBNotificationCenterViewController : UIViewController <SBNCTableViewControllerDelegate, SBUISizeObservingViewDelegate, SBSearchEtceteraMultiplexingViewControllerAppearanceDelegate, SBNotificationCenterWithSearchViewControllerPresentationDelegate, UIGestureRecognizerDelegate, SBDashBoardExternalBehaviorProviding, SBBulletinActionHandler, SBReachabilityObserver>
{
    id <SBNotificationCenterViewControllerDelegate> _delegate;
    UIView *_clippingView;
    UIView *_containerView;
    UIView *_contentView;
    UIView *_backgroundView;
    UIView *_tintView;
    SBNotificationSeparatorView *_bottomSeparator;
    SBNotificationCenterLayoutViewController *_layoutViewController;
    SBNotificationCenterWithSearchViewController *_notificationCenterWithSearchViewController;
    UIStatusBar *_statusBar;
    SBNotificationCenterScrollToTopView *_scrollToTopView;
    SBUIChevronView *_grabberView;
    UIView *_grabberContentView;
    UIView *_grabberBackgroundView;
    UIView *_grabberTintView;
    SBUIChevronView *_registeredGrabberView;
    struct CGRect _grabberContentViewFrameForRegisteredGrabber;
    CDUnknownBlockType _registeredGrabberHideBlock;
    struct {
        unsigned int blursBackground:1;
        unsigned int showsBackground:1;
        unsigned int isBackgroundValid:1;
        unsigned int isGrabberEnabled:1;
        unsigned int isGrabberLockEngaged:1;
        unsigned int viewHitTestsAsOpaque:1;
        unsigned int isViewHitTestingValid:1;
    } _notificationCenterViewControllerFlags;
    _Bool _showingForReachability;
    struct CGPoint _preReachabilityOrigin;
    struct CGPoint _reachabilityOrigin;
    _Bool _preReachabilityGrabberHidden;
    struct CGRect _preReachabilityGrabberFrame;
    struct CGPoint _preReachabilitySeparatorOrigin;
    struct CGPoint _reachabilitySeparatorOrigin;
    UIGestureRecognizer *_tapToCancelReachabilityGestureRecognizer;
    _Bool _allowPartialPulldownForCurrentTransition;
    _Bool _searchIsPresentedForPartialPulldown;
    _Bool _searchIsDismissingFromPartialPulldown;
    double _maxStatusBarOffsetForPartialPulldown;
    UIView *_spotlightBackgroundTopClippingView;
    UIView *_spotlightBackgroundBottomClippingView;
    UIView *_spotlightTransitioningBackgroundView;
    double _lastHapticFeedbackPlayedPosition;
    _Bool _searchFieldNeedsEntryAcceleration;
    _Bool _gestureNeedsRubberbandSpeedup;
}

+ (id)grayControlInteractionTintColor;
@property(nonatomic) __weak id <SBNotificationCenterViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBNotificationCenterWithSearchViewController *notificationCenterWithSearchViewController; // @synthesize notificationCenterWithSearchViewController=_notificationCenterWithSearchViewController;
@property(readonly, nonatomic) SBUIChevronView *grabberView; // @synthesize grabberView=_grabberView;
- (void).cxx_destruct;
- (id)notificationsViewController;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long scrollingStrategy;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (_Bool)_shouldRespondToReachability;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleCancelReachabilityGesture:(id)arg1;
- (void)handleReachabilityModeDeactivated;
- (void)handleReachabilityModeActivated;
- (void)_animateForReachabilityDeactivatedWithHandler:(CDUnknownBlockType)arg1;
- (void)_animateForReachabilityActivatedWithHandler:(CDUnknownBlockType)arg1;
- (void)_performReachabilityTransactionForActivate:(_Bool)arg1 immediately:(_Bool)arg2;
- (void)setSpotlightVisible:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)performScrollTest:(id)arg1 iterations:(long long)arg2 delta:(long long)arg3;
- (_Bool)handleAction:(id)arg1 forBulletin:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (double)contentBottomInset;
- (_Bool)searchIsPresentingOrDismissingForPartialPulldown;
- (void)_resetAdjustedViewPositions;
- (void)_transitionSpotlightBackgroundForPresentation:(_Bool)arg1;
- (void)_addSpotlightBackgroundForPresentation:(_Bool)arg1;
- (id)_newSpotlightBackgroundView;
- (void)searchEtceteraViewController:(id)arg1 willDismissSearchWithReason:(unsigned long long)arg2;
- (void)_updateGrabberAndPageControlForMode:(unsigned long long)arg1;
- (void)searchEtceteraViewController:(id)arg1 didChangeToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)searchEtceteraViewController:(id)arg1 changingToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)searchEtceteraViewController:(id)arg1 willChangeToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (struct CGRect)grabberContentRect;
- (void)updateForChangeInLockedState;
@property(readonly, nonatomic) struct CGRect contentFrame;
- (void)_setContainerFrame:(struct CGRect)arg1;
- (struct CGRect)_containerFrame;
- (struct CGRect)_containerFrame:(_Bool)arg1;
@property(nonatomic) struct UIEdgeInsets clippingInsets;
@property(nonatomic) double contentViewAlpha;
- (void)dismissGrabberView;
- (void)presentGrabberView;
- (struct CGRect)_grabberContentViewFrameForDefaultGrabberPresentation;
- (struct CGRect)_grabberContentViewFrameForRegisteredGrabber;
- (void)abortAnimatedPositionChange;
- (struct CGRect)positionContentForTouchAtLocation:(struct CGPoint)arg1;
- (void)_positionSearchRelatedViewsWithTouchLocation:(double)arg1;
- (double)_speedupOffsetForNotificationPulldown;
- (struct CGPoint)_translatedCenterPointWithOriginalBounds:(struct CGRect)arg1 yTranslation:(double)arg2;
- (double)_scaledValueAtLocation:(double)arg1 withLowerBound:(double)arg2 upperBound:(double)arg3 rangeMin:(double)arg4 rangeMax:(double)arg5;
- (void)dismissPartialPulldownSpotlightAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentPartialPulldownSpotlightAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissSearchForHardwareKeyboardWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentSearchForHardwareKeyboardWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)searchIsDismissingFromPartialPulldown;
- (_Bool)searchIsPresentedFromPartialPulldown;
- (_Bool)shouldPlayFeedbackForNewTouchLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (_Bool)_shouldPlayFeedbackForNewOffset:(double)arg1 oldOffset:(double)arg2 targetValue:(double)arg3;
- (double)minimumTranslationToEndGestureWithReveal;
- (_Bool)shouldPresentSpotlightFromCurrentPositionWithVelocity:(struct CGPoint)arg1;
- (_Bool)_velocityIsSufficientToRevealNotificationCenter:(struct CGPoint)arg1;
- (_Bool)shouldEndGestureWithPresentationWithVelocity:(struct CGPoint)arg1;
- (double)_initialStatusBarSearchFieldOffset;
- (double)_currentDragPosition;
- (void)cleanUpAfterTransition;
- (void)prepareForTransition;
- (void)_setViewHitTestAsOpaque:(_Bool)arg1;
- (id)colorForElement:(long long)arg1;
- (id)_relevanceDateColor;
- (id)_grabberColor;
- (void)disableGrabberLock;
- (_Bool)isGrabberLocked;
@property(nonatomic, getter=isGrabberViewEnabled) _Bool grabberViewEnabled;
- (void)_configureGrabberForSoloMode:(_Bool)arg1;
- (id)unregisterSharedGrabberView;
- (void)registerSharedGrabberView:(id)arg1 withHideBlock:(CDUnknownBlockType)arg2;
- (void)_registerGrabberView:(id)arg1 withHideBlock:(CDUnknownBlockType)arg2;
- (struct CGRect)revealRectForBulletin:(id)arg1;
- (_Bool)shouldAllowInteractiveDismissal;
- (void)prepareLayoutForPresentationFromBanner;
- (void)prepareLayoutForDefaultPresentation;
@property(nonatomic, getter=isSuppressingNotificationUpdates) _Bool suppressesNotificationUpdates;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)sizeObservingView:(id)arg1 didChangeSize:(struct CGSize)arg2;
@property(readonly, nonatomic) long long layoutMode;
- (void)viewDidLoad;
- (void)loadView;
- (void)_loadLayoutViewControllerView;
- (void)_loadNotificationCenterWithSearchViewControllerView;
- (void)_loadScrollToTopView;
- (void)_loadBottomSeparator;
- (void)_loadGrabberContentView;
- (id)_newGrabberView;
- (void)_updateContrastSettingsForBottomSeparator;
- (void)_updateContrastSettingsForGrabberView;
- (void)_loadStatusBar;
- (void)_loadContentView;
- (void)_loadContainerView;
- (void)_loadClippingView;
- (void)_configureView;
- (void)_validateBackgroundViewIfNecessary;
@property(readonly, nonatomic) _UIBackdropView *backdropView;
@property(nonatomic) _Bool blursBackground;
- (_Bool)tintsBackground;
@property(nonatomic) _Bool showsBackground;
- (id)_newTintView;
- (id)_newBackgroundView;
- (id)_newNonBlurredBackgroundViewWithAutoresizing:(_Bool)arg1;
- (long long)_defaultBackdropViewStyle;
@property(readonly, copy, nonatomic) NSSet *visibleContentViewControllers;
- (void)_authenticationStateChanged:(id)arg1;
- (void)_backgroundContrastDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

