//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSectionInfo.h"

@class SBItemInfoLayoutCache;

@interface SBNotificationCenterSectionInfo : SBSectionInfo
{
    SBItemInfoLayoutCache *_layoutCache;
    CDUnknownBlockType _clearPossibleAction;
    CDUnknownBlockType _clearFinalAction;
}

@property(copy, nonatomic) CDUnknownBlockType clearAction; // @synthesize clearAction=_clearFinalAction;
@property(copy, nonatomic) CDUnknownBlockType clearPossibleAction; // @synthesize clearPossibleAction=_clearPossibleAction;
- (void).cxx_destruct;
- (double)heightForReusableViewForNotificationCenterTableViewController:(id)arg1 layoutMode:(long long)arg2 sectionLocation:(long long)arg3;
- (void)invalidateCachedLayoutData;
- (Class)reusableViewClass;

@end

