//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, SBRemoteAlertController;

@protocol SBRemoteAlertControllerDelegate <NSObject>
- (void)queue_remoteAlertController:(SBRemoteAlertController *)arg1 didInvalidateWithReason:(long long)arg2 underlyingError:(NSError *)arg3;
- (void)queue_remoteAlertControllerDidChangeActivationState:(SBRemoteAlertController *)arg1;
@end

