//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSMutableIndexSet, SBApplicationIcon;

@interface SBRelatedDataDeletionAlertItem : SBAlertItem
{
    SBApplicationIcon *_icon;
    NSMutableIndexSet *_relatedDataStores;
    NSMutableIndexSet *_dataStoresToPurge;
    long long _deleteButtonIndex;
}

- (void).cxx_destruct;
- (_Bool)dismissOnLock;
- (_Bool)shouldShowInLockScreen;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)dismissAlertDeletingData:(_Bool)arg1;
- (_Bool)_hasUnconsideredDataStores;
- (unsigned long long)_currentDataStoreCandidate;
- (void)setHasGameKitData:(_Bool)arg1;
- (void)setHasHealthKitData:(_Bool)arg1;
- (id)initWithIcon:(id)arg1;

@end

