//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BSTransaction<SBStartupTransition>, FBSystemService, SBInitialRestartState, SBRestartTransitionRequest, SBStartupTransitionController;

@interface SBRestartManager : NSObject
{
    id <SBRestartManagerDelegate> _delegate;
    SBInitialRestartState *_initialRestartState;
    SBStartupTransitionController *_startupController;
    SBRestartTransitionRequest *_pendingRestartTransitionRequest;
    _Bool _isShuttingDown;
    _Bool _isRestartImminent;
    _Bool _isUserSwitchPending;
    FBSystemService *_systemService;
}

@property(nonatomic, getter=_isUserSwitchPending, setter=_setUserSwitchPending:) _Bool isUserSwitchPending; // @synthesize isUserSwitchPending=_isUserSwitchPending;
@property(readonly, nonatomic) SBRestartTransitionRequest *pendingRestartTransitionRequest; // @synthesize pendingRestartTransitionRequest=_pendingRestartTransitionRequest;
@property(nonatomic) __weak id <SBRestartManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)___waitForeverTillBackBoarddExits;
- (void)_doRestartForTransition:(int)arg1;
- (void)_persistStartupTransitionContextFromRebootContext:(id)arg1;
- (void)_persistStartupTransitionContextFromRestartRequest:(id)arg1;
- (void)_reallyRestartWithTransitionRequest:(id)arg1;
- (void)_restartWithTransitionRequest:(id)arg1;
- (void)_postShutdownNotification;
- (void)_shutdownWithOptions:(unsigned long long)arg1 description:(id)arg2;
- (void)_killAllAppsForPendingExitWithReason:(long long)arg1 description:(id)arg2 expiration:(double)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_exitIsImminent;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)description;
- (void)restartWithTransitionRequest:(id)arg1;
- (void)rebootWithContext:(id)arg1;
- (void)rebootForReason:(id)arg1;
- (void)shutdownForReason:(id)arg1;
- (void)initializeAndRunStartupTransition:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) BSTransaction<SBStartupTransition> *startupTransition; // @dynamic startupTransition;
@property(readonly, nonatomic, getter=isPendingExit) _Bool pendingExit; // @dynamic pendingExit;
- (id)initWithInitialRestartState:(id)arg1;
- (id)_initWithInitialRestartState:(id)arg1 startupController:(id)arg2 systemService:(id)arg3;

@end

