//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@interface SBRestoreFailureAlertItem : SBAlertItem
{
}

- (_Bool)allowInSetup;
- (_Bool)forcesModalAlertAppearance;
- (_Bool)shouldShowInLockScreen;
- (_Bool)allowMenuButtonDismissal;
- (void)performUnlockAction;
- (void)restartSystemEvent;
- (void)_rebootNow;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;

@end

