//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBCenterAppLaunchSettings, SBCenterAppSuspendSettings, SBCrossfadeAppLaunchSettings, SBCrossfadeAppSuspendSettings, SBFolderCloseSettings, SBFolderOpenSettings, SBReducedMotionFadeSettings, SBUnlockSettings;

@interface SBRootAnimationSettings : SBUISettings
{
    SBReducedMotionFadeSettings *_reducedMotionSettings;
    SBUnlockSettings *_unlockSettings;
    SBCenterAppLaunchSettings *_centerLaunchSettings;
    SBCenterAppSuspendSettings *_centerSuspendSettings;
    SBCrossfadeAppLaunchSettings *_crossfadeLaunchSettings;
    SBCrossfadeAppSuspendSettings *_crossfadeSuspendSettings;
    double _maxAppSuspendHintProgress;
    SBFolderOpenSettings *_folderOpenSettings;
    SBFolderCloseSettings *_folderCloseSettings;
    double _maxFolderCloseHintProgress;
}

+ (id)settingsControllerModule;
@property double maxFolderCloseHintProgress; // @synthesize maxFolderCloseHintProgress=_maxFolderCloseHintProgress;
@property(retain) SBFolderCloseSettings *folderCloseSettings; // @synthesize folderCloseSettings=_folderCloseSettings;
@property(retain) SBFolderOpenSettings *folderOpenSettings; // @synthesize folderOpenSettings=_folderOpenSettings;
@property double maxAppSuspendHintProgress; // @synthesize maxAppSuspendHintProgress=_maxAppSuspendHintProgress;
@property(retain) SBCrossfadeAppSuspendSettings *crossfadeSuspendSettings; // @synthesize crossfadeSuspendSettings=_crossfadeSuspendSettings;
@property(retain) SBCrossfadeAppLaunchSettings *crossfadeLaunchSettings; // @synthesize crossfadeLaunchSettings=_crossfadeLaunchSettings;
@property(retain) SBCenterAppSuspendSettings *centerSuspendSettings; // @synthesize centerSuspendSettings=_centerSuspendSettings;
@property(retain) SBCenterAppLaunchSettings *centerLaunchSettings; // @synthesize centerLaunchSettings=_centerLaunchSettings;
@property(retain) SBUnlockSettings *unlockSettings; // @synthesize unlockSettings=_unlockSettings;
@property(retain) SBReducedMotionFadeSettings *reducedMotionSettings; // @synthesize reducedMotionSettings=_reducedMotionSettings;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

