//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIGestureRecognizer.h"

@class BSTimer, NSMutableSet;

@interface SBScreenshotGestureRecognizer : UIGestureRecognizer
{
    BSTimer *_downTimer;
    NSMutableSet *_currentlyPressedTypes;
    _Bool _didGetRequiredSimultaneousDowns;
    double _maximumIntervalBetweenPresses;
}

@property(nonatomic) double maximumIntervalBetweenPresses; // @synthesize maximumIntervalBetweenPresses=_maximumIntervalBetweenPresses;
- (void).cxx_destruct;
- (_Bool)_allRequiredButtonsDown;
- (void)_processPresses:(id)arg1;
- (void)_fail;
- (void)_succeed;
- (void)_resetDelayState;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (void)reset;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

