//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBDateTimeOverrideObserver.h"

@class NSDate, NSString, SBUILegibilityLabel, _UILegibilitySettings;

@interface SBSearchEtceteraDateViewController : UIViewController <SBDateTimeOverrideObserver>
{
    SBUILegibilityLabel *_dateLabel;
    NSDate *_overrideDate;
    _Bool _useMultiLineDate;
    _UILegibilitySettings *_legibilitySettings;
}

@property(nonatomic) _Bool useMultiLineDate; // @synthesize useMultiLineDate=_useMultiLineDate;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void).cxx_destruct;
- (void)_layoutDateLabel;
- (void)_updateDateLabel;
- (id)_dateLabelFont;
- (void)significantTimeChanged:(id)arg1;
- (void)controller:(id)arg1 didChangeOverrideDateFromDate:(id)arg2;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

