//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBSearchEtceteraLayoutViewDelegate.h"
#import "SBViewControllerTransitionContextDelegate.h"
#import "SPUISearchViewControllerDelegate.h"
#import "WGWidgetGroupViewControllerDelegate.h"

@class NCNotificationListContainerViewController, NSHashTable, NSMutableSet, NSString, SBNotificationCenterDestination, SBSearchEtceteraDateViewController, SBSearchEtceteraLayoutView, SBViewControllerTransitionContext, SPUISearchViewController, UINavigationItem, WALockscreenWidgetViewController, WGWidgetGroupViewController;

@interface SBSearchEtceteraIsolatedViewController : UIViewController <SBViewControllerTransitionContextDelegate, SBSearchEtceteraLayoutViewDelegate, SPUISearchViewControllerDelegate, WGWidgetGroupViewControllerDelegate>
{
    unsigned long long _currentMode;
    unsigned long long _supportedModes;
    SBSearchEtceteraLayoutView *_layoutView;
    SPUISearchViewController *_searchViewController;
    WGWidgetGroupViewController *_todayViewController;
    SBNotificationCenterDestination *_notificationCenterDestination;
    NCNotificationListContainerViewController *_notificationListContainerViewController;
    WALockscreenWidgetViewController *_weatherViewController;
    SBSearchEtceteraDateViewController *_dateViewController;
    unsigned long long _transitioningFromMode;
    unsigned long long _transitioningToMode;
    UIViewController *_transitioningFromChildViewController;
    UIViewController *_transitioningToChildViewController;
    unsigned long long _searchDismissalReasonForThisTransition;
    unsigned long long _lastPresentationSource;
    SBViewControllerTransitionContext *_currentTransition;
    id <SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning> _currentTransitionAnimator;
    NSMutableSet *_userInteractionDisabledReasons;
    _Bool _pullToSearchPossible;
    _Bool _pullToSearchRecognizing;
    _Bool transitionedToSearchInteractively;
    _Bool _scrollViewContentOffsetDirty;
    struct CGPoint _scrollViewLastContentOffset;
    long long _isInteractivePopToSearch;
    long long _poppingToSearch;
    long long _pushingOverSearch;
    _Bool _searchControllerRequestedReset;
    NSHashTable *_widgetEffectViews;
    struct {
        unsigned int runningOnPad:1;
        unsigned int delegateRespondsToWillBeginDragging:1;
        unsigned int delegateRespondsToDidScroll:1;
        unsigned int delegateRespondsToWillEndDragging:1;
        unsigned int delegateRespondsToDidEndDragging:1;
        unsigned int delegateRespondsToDidEndDecelerating:1;
        unsigned int delegateRespondsToDidEndScrollingAnimation:1;
        unsigned int delegateRespondsToNewCustomBackgroundViewForItemInList:1;
        unsigned int didDelaySearchWillDismiss:1;
    } _isolatedViewControllerFlags;
    _Bool _widgetsUseCustomBackgroundViews;
    unsigned long long _currentStyle;
    id <SBSearchEtceteraIsolatedViewControllerAppearanceDelegate> _delegate;
    id <WGWidgetGroupViewControllerDelegate> _widgetGroupDelegate;
    id <SPUISearchViewControllerDelegate> _searchDelegate;
    unsigned long long _searchViewPresentationSourceForNextTransition;
    unsigned long long _searchViewDismissalReasonForNextTransition;
    unsigned long long _defaultMode;
    unsigned long long _defaultSearchViewPresentationSource;
    unsigned long long _defaultSearchViewDismissalReason;
}

+ (Class)__viewClass;
+ (Class)viewClass;
+ (id)sharedInstance;
@property(nonatomic) _Bool widgetsUseCustomBackgroundViews; // @synthesize widgetsUseCustomBackgroundViews=_widgetsUseCustomBackgroundViews;
@property(nonatomic) unsigned long long defaultSearchViewDismissalReason; // @synthesize defaultSearchViewDismissalReason=_defaultSearchViewDismissalReason;
@property(nonatomic) unsigned long long defaultSearchViewPresentationSource; // @synthesize defaultSearchViewPresentationSource=_defaultSearchViewPresentationSource;
@property(nonatomic) unsigned long long defaultMode; // @synthesize defaultMode=_defaultMode;
@property(nonatomic) unsigned long long searchViewDismissalReasonForNextTransition; // @synthesize searchViewDismissalReasonForNextTransition=_searchViewDismissalReasonForNextTransition;
@property(nonatomic) unsigned long long searchViewPresentationSourceForNextTransition; // @synthesize searchViewPresentationSourceForNextTransition=_searchViewPresentationSourceForNextTransition;
@property(nonatomic) __weak id <SPUISearchViewControllerDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
@property(nonatomic) __weak id <WGWidgetGroupViewControllerDelegate> widgetGroupDelegate; // @synthesize widgetGroupDelegate=_widgetGroupDelegate;
@property(nonatomic) __weak id <SBSearchEtceteraIsolatedViewControllerAppearanceDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long currentStyle; // @synthesize currentStyle=_currentStyle;
@property(retain, nonatomic, getter=_notificationCenterDestination, setter=_setNotificationCenterDestination:) SBNotificationCenterDestination *notificationCenterDestination; // @synthesize notificationCenterDestination=_notificationCenterDestination;
@property(retain, nonatomic, getter=_notificationListContainerViewController, setter=_setNotificationListContainerViewController:) NCNotificationListContainerViewController *notificationListContainerViewController; // @synthesize notificationListContainerViewController=_notificationListContainerViewController;
@property(retain, nonatomic, getter=_searchViewController, setter=_setSearchViewController:) SPUISearchViewController *searchViewController; // @synthesize searchViewController=_searchViewController;
@property(retain, nonatomic, getter=_todayViewController, setter=_setTodayViewController:) WGWidgetGroupViewController *todayViewController; // @synthesize todayViewController=_todayViewController;
- (void).cxx_destruct;
- (void)_containingNavigationControllerDidDisappear;
- (void)_updateWeatherAndDateViewOffsetsForScrollView:(id)arg1;
- (void)_updateTodayViewContentInsets;
- (void)_updateTodayViewAppearanceForCurrentStyle;
- (_Bool)_shouldNotifyWeatherWidgetForAppearanceChanges;
- (void)_setOrientationLockOverrideForSearch:(_Bool)arg1;
- (void)_willDeactivateHosting;
- (void)_setUserInteractionDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)_postNotificationForSearchVisibilityChanged;
- (unsigned long long)_lastPresentationSource;
- (unsigned long long)_currentPresentationSource;
- (_Bool)_todayViewIsVisible;
- (_Bool)_searchIsVisible;
- (_Bool)_deviceSupportsWeatherDisplay;
- (void)_updateWidgetLegibility:(id)arg1;
- (void)_updateSearchLegibility:(id)arg1;
- (void)_updateDateViewLegibility:(id)arg1;
- (void)_updateWeatherLegibility:(id)arg1;
- (void)_updateAccessoryLegibility;
- (void)_popToRootViewControllerForSearchIfNeeded:(_Bool)arg1;
- (_Bool)isTransitioningFromSpotlight;
- (_Bool)isTransitioningToSpotlight;
- (_Bool)isShowingSpotlight;
- (void)_resetAfterAnimatedScroll;
- (void)_scrollToEnterSpotlight;
- (void)_exitSpotlightForReason:(unsigned long long)arg1 animated:(_Bool)arg2 animationBegan:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_exitSpotlightForReason:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_exitSpotlightForReason:(unsigned long long)arg1;
- (void)_enterSpotlightInteractively;
- (void)_enterSpotlightAnimated:(_Bool)arg1 animationBegan:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_enterSpotlightAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)transitionDidFinish:(id)arg1;
- (void)transitionWillFinish:(id)arg1;
- (void)transitionDidReverse:(id)arg1;
- (void)transitionWillBegin:(id)arg1;
- (void)_setCurrentMode:(unsigned long long)arg1 animated:(_Bool)arg2 interactive:(_Bool)arg3 animations:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;
- (_Bool)_shouldDelaySearchWillDismissWithReason:(unsigned long long)arg1;
- (_Bool)_shouldPresentSearchFromSource:(unsigned long long)arg1;
- (_Bool)_isPushingOverSearch:(id)arg1;
- (_Bool)_isPoppingToSearch:(id)arg1;
- (_Bool)_isInteractivePopToSearch:(id)arg1;
- (void)_resetStateForNavigationControllerTransitionTo:(id)arg1;
- (void)_captureStateForNavigationControllerTransitionTo:(id)arg1;
- (void)_propagateLifecycleMethodsOnDidChangeToModeAnimated:(_Bool)arg1 reverse:(_Bool)arg2;
- (void)_propagateLifecycleMethodsOnDidChangeToModeAnimated:(_Bool)arg1;
- (void)_propagateLifecycleMethodsOnWillChangeToModeAnimated:(_Bool)arg1 reverse:(_Bool)arg2;
- (void)_propagateLifecycleMethodsOnWillChangeToModeAnimated:(_Bool)arg1;
- (_Bool)isTransitioning;
- (void)_performStateChangeForEligibleContainedViewControllers:(CDUnknownBlockType)arg1;
- (id)_viewControllersToNotifyOfStateChanges;
- (id)viewControllerForMode:(unsigned long long)arg1;
- (void)_didChangeToMode:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)_setMode:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)_willChangeToMode:(unsigned long long)arg1 animated:(_Bool)arg2;
- (unsigned long long)_searchPresentationSourceForThisTransition;
- (unsigned long long)_searchDismissalReasonForThisTransition;
- (void)_cleanupTransitionStateTracking;
- (void)_captureTransitionStateTrackingForTransitionToMode:(unsigned long long)arg1;
- (_Bool)_onlySupportsSearch;
- (unsigned long long)_nextModeIfResigningCurrentMode;
- (void)_weatherWidgetVisibilityChanged;
- (void)_setDateViewController:(id)arg1;
- (void)_setWeatherViewController:(id)arg1;
- (void)_setNotificationViewController:(id)arg1;
- (void)searchEtceteraLayoutView:(id)arg1 didChangeToMode:(unsigned long long)arg2;
- (void)searchEtceteraLayoutView:(id)arg1 willChangeToMode:(unsigned long long)arg2;
- (void)handleScrollingEnded:(id)arg1;
- (void)handleDraggingWillEndWithTargetContentOffset:(inout struct CGPoint *)arg1 forScrollView:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (id)_dateMovingScrollView;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)pullDownSearchGestureDraggingFromTopOfScrollView:(id)arg1;
- (double)pullDownSearchGesturePercentComplete;
- (double)pullDownSearchGestureYOffset;
- (struct UIEdgeInsets)widgetListViewEdgeInsetsIncludingSearchHeader:(_Bool)arg1;
- (id)additionalBundleIdentifiersForAttribution:(id)arg1;
- (id)widgetGroupViewController:(id)arg1 newCustomBackgroundViewForItem:(id)arg2 inScrollView:(id)arg3;
- (void)destination:(id)arg1 requestsClearingNotificationRequests:(id)arg2;
- (void)destination:(id)arg1 executeAction:(id)arg2 forNotificationRequest:(id)arg3 withParameters:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (id)notificationSectionSettingsForDestination:(id)arg1 forSectionIdentifier:(id)arg2;
- (id)notificationSectionSettingsForDestination:(id)arg1;
- (void)resetSearchView;
- (void)dismissSearchViewWithReason:(unsigned long long)arg1;
- (void)searchFieldDidFocus;
- (void)_statusBarWasTapped:(id)arg1;
- (void)_createMultiplexedChildViewControllers;
@property(readonly, retain, nonatomic) SBSearchEtceteraLayoutView *contentView;
@property(nonatomic) unsigned long long currentMode;
- (unsigned long long)supportedModes;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)_containedViewController:(id)arg1 didDisappear:(_Bool)arg2;
- (void)_containedViewController:(id)arg1 willDisappear:(_Bool)arg2;
- (void)_containedViewController:(id)arg1 didAppear:(_Bool)arg2;
- (void)_containedViewController:(id)arg1 willAppear:(_Bool)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (struct CGSize)sizeForChildContentContainer:(id)arg1 withParentContainerSize:(struct CGSize)arg2;
@property(readonly, nonatomic) UINavigationItem *navigationItem;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

