//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBSearchEtceteraLayoutView;

@protocol SBSearchEtceteraLayoutViewDelegate <NSObject>

@optional
- (void)searchEtceteraLayoutView:(SBSearchEtceteraLayoutView *)arg1 didChangeToMode:(unsigned long long)arg2;
- (void)searchEtceteraLayoutView:(SBSearchEtceteraLayoutView *)arg1 willChangeToMode:(unsigned long long)arg2;
@end

