//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBSearchEtceteraMetrics : NSObject
{
}

+ (_Bool)_isPortrait;
+ (double)minYofClippableContent;
+ (_Bool)shouldUseMultiLineDateViewForStyle:(unsigned long long)arg1;
+ (_Bool)shouldShowDateViewForStyle:(unsigned long long)arg1;
+ (_Bool)shouldShowWeatherViewForStyle:(unsigned long long)arg1;
+ (double)verticalSpacingBetweenWidgets;
+ (double)topContentInsetForSearchNavigationBar:(id)arg1;
+ (void)adjustTargetContentOffset:(inout struct CGPoint *)arg1 forScrollView:(id)arg2 withDefaultRestingOffset:(double)arg3;
+ (double)defaultRestingOffsetForStyle:(unsigned long long)arg1 navigationBarInset:(double)arg2;
+ (struct UIEdgeInsets)contentInsetsForStyle:(unsigned long long)arg1 bounds:(struct CGRect)arg2 contentSize:(struct CGSize)arg3 navigationBarInset:(double)arg4;
+ (_Bool)shouldAddNavBarInsetForStyle:(unsigned long long)arg1;
+ (_Bool)shouldAddTopInsetForStyle:(unsigned long long)arg1;
+ (_Bool)isShowingTwoWidgetColumns;

@end

