//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBModalViewControllerStackDelegate.h"
#import "UIAlertControllerCoordinatedActionPerforming.h"
#import "_SBAlertControllerDelegate.h"

@class NSString, SBAlertItem, SBModalViewControllerStack, UIWindow;

@interface SBSharedModalAlertItemPresenter : NSObject <_SBAlertControllerDelegate, SBModalViewControllerStackDelegate, UIAlertControllerCoordinatedActionPerforming>
{
    id <SBFLockOutStatusProvider> _lockOutProvider;
    SBModalViewControllerStack *_modalViewControllerStack;
    UIWindow *_window;
}

@property(retain, nonatomic, getter=_modalViewControllerStack, setter=_setModalViewControllerStack:) SBModalViewControllerStack *modalViewControllerStack; // @synthesize modalViewControllerStack=_modalViewControllerStack;
- (void).cxx_destruct;
- (void)alertControllerDidDisappear:(id)arg1;
- (void)_performActionForAlertController:(id)arg1 invokeActionBlock:(CDUnknownBlockType)arg2 dismissControllerBlock:(CDUnknownBlockType)arg3;
- (void)modalViewControllerStack:(id)arg1 didDismissViewController:(id)arg2;
- (void)modalViewControllerStack:(id)arg1 willDismissViewController:(id)arg2;
- (void)modalViewControllerStack:(id)arg1 didPresentViewController:(id)arg2;
- (void)modalViewControllerStack:(id)arg1 willPresentViewController:(id)arg2;
- (void)dismissAlertItem:(id)arg1 animated:(_Bool)arg2;
- (void)presentAlertItem:(id)arg1 isLocked:(_Bool)arg2 animated:(_Bool)arg3;
@property(readonly, nonatomic) SBAlertItem *currentlyPresentedAlertItem;
- (id)initWithLockOutProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

