//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UINavigationBar, UITextView;

@interface SBSMSClass0AboutViewController : UIViewController
{
    UITextView *_aboutContentView;
    UINavigationBar *_navigationBar;
}

- (void).cxx_destruct;
- (id)formattedAboutText;
- (void)doneButtonTapped:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;

@end

