//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseSoftwareUpdateAlertItem.h"

@class NSString, NSTimer, SBSoftwareUpdateInstallOperationLifeCycleHandler, SBSoftwareUpdateInstallOptions, SUAutoInstallOperation, SUDownload;

@interface SBSoftwareUpdateInstallAlertItem : SBBaseSoftwareUpdateAlertItem
{
    unsigned long long _alertStyle;
    _Bool _undimScreen;
    _Bool _choseInstallTonight;
    SBSoftwareUpdateInstallOptions *_installOptions;
    SUDownload *_download;
    _Bool _scheduleInstallAlertRepopOnDismiss;
    NSString *_repopReason;
    NSTimer *_countdownTimer;
    unsigned long long _timeLeftUntilInstall;
    SBSoftwareUpdateInstallOperationLifeCycleHandler *_tryTonightOperationWrapper;
}

@property(retain, nonatomic, getter=_tryTonightOperationWrapper, setter=_setTryTonightOperationWrapper:) SBSoftwareUpdateInstallOperationLifeCycleHandler *tryTonightOperationWrapper; // @synthesize tryTonightOperationWrapper=_tryTonightOperationWrapper;
@property(readonly, nonatomic) unsigned long long style; // @synthesize style=_alertStyle;
- (void).cxx_destruct;
- (void)_countdownTimerFired;
- (void)_updateBodyTextForCountdown;
- (id)_bodyTextToModelSpecificLocalizedKey:(id)arg1;
- (void)_scheduleInstallAlertRepopOnDismissWithReason:(id)arg1;
- (void)_installUpdateNowFromTimer:(_Bool)arg1;
- (_Bool)_shouldCountdown;
- (void)_clearCountdownTimer;
- (void)_setTryTonightOperation:(id)arg1;
- (id)_stringFromAlertStyle:(unsigned long long)arg1;
- (void)performUnlockAction;
- (_Bool)shouldShowInLockScreen;
- (id)shortLockLabel;
- (id)lockLabel;
- (_Bool)undimsScreen;
- (_Bool)dismissOnLock;
- (_Bool)allowLockScreenDismissal;
- (_Bool)allowMenuButtonDismissal;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)willDeactivateForReason:(int)arg1;
- (void)_setOccluded:(_Bool)arg1;
- (id)description;
@property(readonly, nonatomic) __weak SUAutoInstallOperation *tryTonightOperation;
- (void)dealloc;
- (id)initWithDownload:(id)arg1 style:(unsigned long long)arg2 softwareUpdateController:(id)arg3 tryTonightInstallOperation:(id)arg4 installOptions:(id)arg5;
- (id)initWithDownload:(id)arg1 softwareUpdateController:(id)arg2;

@end

