//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseSoftwareUpdateInstallFailureAlertItem.h"

@class NSError;

@interface SBSoftwareUpdateUnableToInstallAlertItem : SBBaseSoftwareUpdateInstallFailureAlertItem
{
    _Bool _unableToInstallDueToInsufficientDiskSpace;
    NSError *_error;
}

@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (_Bool)forcesModalAlertAppearance;
- (_Bool)allowInSetup;
- (_Bool)dismissOnLock;
- (_Bool)allowMenuButtonDismissal;
- (_Bool)shouldShowInLockScreen;
- (_Bool)reappearsAfterLock;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)buildDefaultSheetWithBody:(id)arg1 isLocked:(_Bool)arg2;
- (void)buildUnavailableSheet;
- (void)installNowAction;
- (void)cancelAction;

@end

