//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSystemServiceFacility.h"

@interface SBSystemServiceServer : FBSystemServiceFacility
{
    id <SBSystemServiceServerBiometricsDelegate> _biometricsDelegate;
    id <SBSystemServiceServerHardwareButtonDelegate> _hardwareButtonDelegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <SBSystemServiceServerHardwareButtonDelegate> hardwareButtonDelegate; // @synthesize hardwareButtonDelegate=_hardwareButtonDelegate;
@property(nonatomic) __weak id <SBSystemServiceServerBiometricsDelegate> biometricsDelegate; // @synthesize biometricsDelegate=_biometricsDelegate;
- (void).cxx_destruct;
- (void)_handleHardwareButtonGetHapticType:(id)arg1 fromClient:(id)arg2;
- (void)_handleHardwareButtonSetHapticType:(id)arg1 fromClient:(id)arg2;
- (void)_handleHardwareButtonSetPressEventMask:(id)arg1 fromClient:(id)arg2;
- (void)_handleHardwareButtonAcquireAssertionMessage:(id)arg1 fromClient:(id)arg2;
- (void)_handleBiometricsFetchUnlockCredentialSetMessage:(id)arg1 fromClient:(id)arg2;
- (void)noteDidReceiveMessage:(id)arg1 withType:(long long)arg2 fromClient:(id)arg3;
- (void)noteClientDidDisconnect:(id)arg1;
- (void)dealloc;
- (id)init;

@end

