//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UITableViewCellActionButton.h"

@class SBNotificationSeparatorView, UIImageView;

@interface SBTableViewCellDismissActionButton : _UITableViewCellActionButton
{
    UIImageView *_dismissImageView;
    SBNotificationSeparatorView *_topSeparatorView;
    SBNotificationSeparatorView *_bottomSeparatorView;
    _Bool _shouldUseNarrowWidth;
    _Bool _drawsTopSeparator;
    _Bool _drawsBottomSeparator;
    Class _separatorClass;
}

@property(retain, nonatomic) SBNotificationSeparatorView *bottomSeparatorView; // @synthesize bottomSeparatorView=_bottomSeparatorView;
@property(retain, nonatomic) SBNotificationSeparatorView *topSeparatorView; // @synthesize topSeparatorView=_topSeparatorView;
@property(nonatomic) _Bool drawsBottomSeparator; // @synthesize drawsBottomSeparator=_drawsBottomSeparator;
@property(nonatomic) _Bool drawsTopSeparator; // @synthesize drawsTopSeparator=_drawsTopSeparator;
@property(retain, nonatomic) Class separatorClass; // @synthesize separatorClass=_separatorClass;
@property(nonatomic) _Bool shouldUseNarrowWidth; // @synthesize shouldUseNarrowWidth=_shouldUseNarrowWidth;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

