//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBTreeNodeViewControllerTransitionObserver.h"

@class SBTreeNodeViewController;

@protocol SBTreeNodeViewControllerDelegate <SBTreeNodeViewControllerTransitionObserver>
- (SBTreeNodeViewController *)treeNodeViewController:(SBTreeNodeViewController *)arg1 viewControllerForChildTreeNode:(id <SBTreeNode>)arg2;

@optional
- (id <UIViewControllerInteractiveTransitioning>)treeNodeViewController:(SBTreeNodeViewController *)arg1 interactionControllerForAnimationController:(id <UIViewControllerAnimatedTransitioning>)arg2;
- (id <UIViewControllerAnimatedTransitioning>)treeNodeViewController:(SBTreeNodeViewController *)arg1 animationControllerForOperation:(long long)arg2 animated:(_Bool)arg3 fromViewController:(SBTreeNodeViewController *)arg4 fromTreeNode:(id <SBTreeNode>)arg5 toViewController:(SBTreeNodeViewController *)arg6 toTreeNode:(id <SBTreeNode>)arg7;
- (id <SBTreeNode>)treeNodeViewController:(SBTreeNodeViewController *)arg1 destinationExpandedTreeNodeForTargetTreeNode:(id <SBTreeNode>)arg2;
- (id <SBTreeNode>)treeNodeViewController:(SBTreeNodeViewController *)arg1 targetExpandedTreeNodeForProposedTreeNode:(id <SBTreeNode>)arg2;
- (void)treeNodeViewController:(SBTreeNodeViewController *)arg1 dismissedChildTreeNode:(id <SBTreeNode>)arg2;
- (void)treeNodeViewController:(SBTreeNodeViewController *)arg1 selectedChildTreeNode:(id <SBTreeNode>)arg2;
@end

