//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIAnimationController.h"

@interface SBUIStarkDosidoNowPlayingAnimation : SBUIAnimationController
{
}

- (id)initFromAlertImpersonator:(id)arg1 toNowPlayingWithStarkScreenController:(id)arg2;
- (id)initFromNowPlayingToAlertImpersonator:(id)arg1 starkScreenController:(id)arg2;
- (id)initFromApp:(id)arg1 toNowPlayingWithStarkScreenController:(id)arg2;
- (id)initFromNowPlayingToApp:(id)arg1 starkScreenController:(id)arg2;
- (id)initFromNowPlayingToNowPlayingWithStarkScreenController:(id)arg1;
- (void)_commonInitWithTransitionContextProvider:(id)arg1 starkScreenController:(id)arg2 waitForNowPlaying:(_Bool)arg3 initializationParametersBlock:(CDUnknownBlockType)arg4;

@end

