//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIAnimationController.h"

@interface SBUIStarkZoomUpNowPlayingFromHomeAnimation : SBUIAnimationController
{
}

- (_Bool)_waitsForApplicationActivationIfNecessary;
- (id)initWithActivatingApp:(id)arg1 alertImpersonator:(id)arg2 starkScreenController:(id)arg3;

@end

