//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class NSMutableArray, SBLockScreenClippedSlideController, SBLockScreenViewControllerBase, SBSceneLayoutAnimationWrapperView;

@interface SBUILockscreenSlideAnimationController : SBUIMainScreenAnimationController
{
    int _transitionStyle;
    SBLockScreenViewControllerBase *_lockscreenViewController;
    SBLockScreenClippedSlideController *_lockscreenClippedSlideController;
    SBSceneLayoutAnimationWrapperView *_animationWrapperView;
    NSMutableArray *_appsNeedingContextHosting;
    double _animationDuration;
    _Bool _fromCC;
    _Bool _fromNC;
    _Bool _finishedSliding;
    _Bool _waitForAppActivationForContextHostView;
}

- (void).cxx_destruct;
- (id)description;
- (void)_maybeReportAnimationFinished;
- (void)_finishedSliding;
- (_Bool)_areApplicationLaunchesFinished;
- (void)_applicationDependencyStateChanged;
- (id)animationSettings;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependencies;
- (_Bool)_waitsForApplicationActivationIfNecessary;
- (void)_willSetupStartDependencies;
- (void)dealloc;
- (id)initWithTransitionContextProvider:(id)arg1;
- (void)_setup:(id)arg1 transitionStyle:(int)arg2;

@end

