//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIWorkspaceAnimationController.h"

@class SBWorkspaceTransitionRequest;

@interface SBUIMainScreenAnimationController : SBUIWorkspaceAnimationController
{
}

- (void)_cleanupAnimation;
- (void)_removeWallpaperAnimationPriorityWithFactory:(id)arg1;
- (void)_begin;
- (void)_dismissBannerAnimated:(_Bool)arg1;
- (_Bool)_shouldDismissBanner;
- (void)__startAnimation;
- (id)_primaryAppOrAnyAppFromSet:(id)arg1;
- (id)_getTransitionWindow;
- (id)deactivatingApp;
- (id)activatingApp;
@property(readonly, nonatomic) SBWorkspaceTransitionRequest *transitionRequest;
- (id)initWithWorkspaceTransitionRequest:(id)arg1;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

