//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIAnimationZoomApp.h"

@class SBSceneLayoutElementAnimationWrapperView;

@interface SBUIAnimationZoomDownApp : SBUIAnimationZoomApp
{
    SBSceneLayoutElementAnimationWrapperView *_primaryAppView;
}

- (void).cxx_destruct;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (_Bool)_prefersSceneSnapshot;
- (void)_prepareAnimation;
- (void)setupInteractiveSideAppAnimationIfNecessary;
- (void)_setupCoordinatingTransitions;
- (id)initWithTransitionContextProvider:(id)arg1 zoomDirection:(unsigned long long)arg2;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

