//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class SBAppStatusBarSettingsAssertion, SBLockScreenViewControllerBase, SBMainAlertManager, SBWorkspaceAlert;

@interface SBUIAnimationFadeAlertToLockscreen : SBUIMainScreenAnimationController
{
    SBLockScreenViewControllerBase *_lockScreenViewController;
    SBWorkspaceAlert *_deactivatingAlert;
    SBMainAlertManager *_alertManager;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
}

- (void).cxx_destruct;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (double)animationDelay;
- (double)animationDuration;
- (void)_prepareAnimation;
- (id)animationSettings;
- (void)dealloc;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

