//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBIconIndexNodeObserver.h"

@class NSString, SBFMappedImageCache, SBIconController, SBIconModel, SBWallpaperController;

@interface SBWallpaperPreviewSnapshotCache : NSObject <SBIconIndexNodeObserver>
{
    SBWallpaperController *_wallpaperController;
    SBFMappedImageCache *_imageCache;
    long long _invalidatedLocations;
    SBIconController *_iconController;
    SBIconModel *_model;
}

- (void).cxx_destruct;
- (id)_lockScreenSnapshotProvider;
- (id)_homeScreenSnapshotProvider;
- (void)_backlightFadeFinished;
- (void)_modelDidLayout;
- (void)_modelWillLayout;
- (void)node:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)node:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (void)regenerateSnapshotsForLocations:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)homeScreenSnapshot;
- (id)lockScreenSnapshot;
- (void)invalidateSnapshotsForLocations:(long long)arg1;
- (void)dealloc;
- (id)initWithImageCache:(id)arg1 iconController:(id)arg2 wallpaperController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

