//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 15 2013 15:37:37).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBTransaction.h"

@class FBSDisplay, NSMutableSet, SBAlertManager, SBSceneLayoutViewController, SBUIAnimationController, SBWorkspaceTransitionRequest;

@interface SBWorkspaceTransaction : SBTransaction
{
    NSMutableSet *_slaveTransactions;
    SBUIAnimationController *_suggestedAnimationController;
    _Bool _clearsCompletionAsynchronously;
    FBSDisplay *_display;
    SBWorkspaceTransitionRequest *_transitionRequest;
    SBAlertManager *_alertManager;
    SBSceneLayoutViewController *_layoutController;
}

@property(nonatomic) _Bool clearsCompletionAsynchronously; // @synthesize clearsCompletionAsynchronously=_clearsCompletionAsynchronously;
@property(retain, nonatomic) SBUIAnimationController *suggestedAnimationController; // @synthesize suggestedAnimationController=_suggestedAnimationController;
@property(readonly, nonatomic) SBSceneLayoutViewController *layoutController; // @synthesize layoutController=_layoutController;
@property(readonly, nonatomic) SBWorkspaceTransitionRequest *transitionRequest; // @synthesize transitionRequest=_transitionRequest;
@property(readonly, nonatomic) SBAlertManager *alertManager; // @synthesize alertManager=_alertManager;
@property(readonly, nonatomic) FBSDisplay *display; // @synthesize display=_display;
- (void).cxx_destruct;
- (id)slaveTransactions;
- (void)addSlaveTransaction:(id)arg1;
- (void)_performDeviceCoherencyCheck;
- (id)_customizedDescriptionProperties;
- (void)_didComplete;
- (void)performAdditionalTransition:(id)arg1;
- (void)cancelAdditionalTransition:(id)arg1;
- (void)prepareToPerformAdditionalTransition:(id)arg1;
- (_Bool)canPerformAdditionalTransition:(id)arg1;
- (void)keepAliveForAsyncBlock:(CDUnknownBlockType)arg1;
- (id)initWithTransitionRequest:(id)arg1;
- (id)init;

@end

